---
- name: Build a Samba Docker Image for Anonymous Shares
  hosts: localhost
  connection: local

  tasks:
  - name: Create temporary directory
    tempfile:
      state: directory
    register: tempdir

  - name: Create Dockerfile
    copy:
      dest: "{{ tempdir.path }}/Dockerfile"
      content: |
        FROM debian:latest
        RUN apt-get update && apt-get install -y samba
        RUN mkdir /srv/media
        RUN mkdir /srv/public
        RUN mkdir /srv/shared
        COPY smb.conf /etc/samba/smb.conf
        EXPOSE 445
        CMD ["/usr/sbin/smbd", "-i", "-s", "/etc/samba/smb.conf"]

  - name: Create smb.conf for anonymous shares
    copy:
      dest: "{{ tempdir.path }}/smb.conf"
      content: |
        [global]
          workgroup = WORKGROUP
          server string = %h
          security = user
          guest account = nobody
          map to guest = bad user

        [media]
          path = /srv/media
          comment = Movies and Music
          browsable = no
          public = yes
          writable = no
          guest ok = yes

        [public]
          path = /srv/public
          comment = Public Files
          browsable = yes
          public = yes
          writable = no
          guest ok = yes

        [shared]
          path = /srv/shared
          comment = Shared Files
          browsable = no
          public = yes
          writable = yes
          guest ok = yes
          create mask = 644
          directory mask = 755

  - name: Build the image
    shell:
      cmd: docker build -t davescodemusings/samba-anon {{ tempdir.path }}

  - name: Verify image exists
    shell:
      cmd: docker images | grep samba-anon

  - name: Clean up temp files
    file:
      path: "{{ tempdir.path }}"
      state: absent
